exclude:
  - node_modules
  - script

sass:
  style: :compressed

theme: jekyll-theme-primer

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

github:
  private: false
  license:
    name: MIT
  source:
    branch: "master"
    path: "/"
  repository_url: "https://github.com/tarunsachdeva/blog"
  
title: Tarun Sachdeva
description: Blog


baseurl: ""
production_url : http://tarunsachdeva.com/
BASE_PATH : http://tarunsachdeva.com/
permalink: /:year:month:day/:title:output_ext
date_format: "%b %-d, %Y"
paginate: 5
paginate_path: "/page:num/"
google_analytics: true